// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TabuAI.Infrastructure.Data;

#nullable disable

namespace TabuAI.Infrastructure.Migrations
{
    [DbContext(typeof(TabuAIDbContext))]
    [Migration("20260308181740_UpdateSeedDataWithNewCategories")]
    partial class UpdateSeedDataWithNewCategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TabuAI.Domain.Entities.ActivityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("uuid");

                    b.Property<int?>("ScoreEarned")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("TabuAI.Domain.Entities.Badge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("RequiredValue")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Badges");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f4a9b0c1-4567-8901-2301-234567890abc"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "İlk oyununu tamamladın!",
                            IconUrl = "/badges/first-game.svg",
                            IsActive = true,
                            Name = "İlk Adım",
                            RequiredValue = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("a5b0c1d2-5678-9012-3412-34567890abcd"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "10 mükemmel prompt yazdın!",
                            IconUrl = "/badges/perfect-prompts.svg",
                            IsActive = true,
                            Name = "Prompt Ustası",
                            RequiredValue = 10,
                            Type = 3
                        },
                        new
                        {
                            Id = new Guid("b6c1d2e3-6789-0123-4523-4567890abcde"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "50 oyunda hiç tabu kelime kullanmadın!",
                            IconUrl = "/badges/tabu-avoidance.svg",
                            IsActive = true,
                            Name = "Tabu Kaçkını",
                            RequiredValue = 50,
                            Type = 5
                        });
                });

            modelBuilder.Entity("TabuAI.Domain.Entities.Challenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChallengedId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChallengerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("VersusGameId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WordId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChallengedId");

                    b.HasIndex("ChallengerId");

                    b.HasIndex("VersusGameId");

                    b.HasIndex("WordId");

                    b.ToTable("Challenges");
                });

            modelBuilder.Entity("TabuAI.Domain.Entities.Friendship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AddresseeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AddresseeId");

                    b.HasIndex("RequesterId", "AddresseeId")
                        .IsUnique();

                    b.ToTable("Friendships");
                });

            modelBuilder.Entity("TabuAI.Domain.Entities.GameAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AiFeedback")
                        .HasColumnType("text");

                    b.Property<string>("AiGuess")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<int?>("PromptQuality")
                        .HasColumnType("integer");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<string>("Suggestions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserPrompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameSessionId");

                    b.ToTable("GameAttempts");
                });

            modelBuilder.Entity("TabuAI.Domain.Entities.GameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AiResponse")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCorrectGuess")
                        .HasColumnType("boolean");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("TimeSpent")
                        .HasColumnType("interval");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserPrompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WordId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WordId");

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("TabuAI.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("FacebookId")
                        .HasColumnType("text");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("integer");

                    b.Property<int>("GamesWon")
                        .HasColumnType("integer");

                    b.Property<string>("GoogleId")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("TotalScore")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("FacebookId")
                        .IsUnique();

                    b.HasIndex("GoogleId")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Admin User",
                            Email = "admin@tabuai.com",
                            GamesPlayed = 0,
                            GamesWon = 0,
                            IsActive = true,
                            Level = 1,
                            PasswordHash = "$2a$11$N9qo8uLOickgx2ZMRZoMyeIjZAgwd966VQRfAk5U5Z6.t.15v8vS6",
                            Role = 2,
                            TotalScore = 0,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("TabuAI.Domain.Entities.UserBadge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BadgeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EarnedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BadgeId");

                    b.HasIndex("UserId", "BadgeId")
                        .IsUnique();

                    b.ToTable("UserBadges");
                });

            modelBuilder.Entity("TabuAI.Domain.Entities.UserStatistic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("MetricName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserStatistics");
                });

            modelBuilder.Entity("TabuAI.Domain.Entities.VersusGame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Player1Attempts")
                        .HasColumnType("integer");

                    b.Property<Guid?>("Player1GameSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Player1Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Player1Score")
                        .HasColumnType("integer");

                    b.Property<int>("Player2Attempts")
                        .HasColumnType("integer");

                    b.Property<Guid?>("Player2GameSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("Player2Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Player2Score")
                        .HasColumnType("integer");

                    b.Property<string>("RoomCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("WinnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WordId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Player1GameSessionId");

                    b.HasIndex("Player1Id");

                    b.HasIndex("Player2GameSessionId");

                    b.HasIndex("Player2Id");

                    b.HasIndex("RoomCode")
                        .IsUnique();

                    b.HasIndex("WordId");

                    b.ToTable("VersusGames");
                });

            modelBuilder.Entity("TabuAI.Domain.Entities.Word", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("TabuWords")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetWord")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Words");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d1b6a7b8-1234-5678-90ab-cdef12345678"),
                            Category = "Ulaşım",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 1,
                            IsActive = true,
                            TabuWords = "[\"hava\",\"kanat\",\"yolcu\",\"pilot\",\"u\\u00E7mak\"]",
                            TargetWord = "Uçak"
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-111111111111"),
                            Category = "Ulaşım",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 1,
                            IsActive = true,
                            TabuWords = "[\"ray\",\"vagon\",\"istasyon\",\"lokomotif\",\"bilet\"]",
                            TargetWord = "Tren"
                        },
                        new
                        {
                            Id = new Guid("a2222222-2222-2222-2222-222222222222"),
                            Category = "Ulaşım",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 1,
                            IsActive = true,
                            TabuWords = "[\"pedal\",\"tekerlek\",\"zincir\",\"gidon\",\"s\\u00FCrmek\"]",
                            TargetWord = "Bisiklet"
                        },
                        new
                        {
                            Id = new Guid("c2a7b8c9-2345-6789-01cd-ef1234567890"),
                            Category = "Teknoloji",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 1,
                            IsActive = true,
                            TabuWords = "[\"ekran\",\"klavye\",\"fare\",\"i\\u015Flemci\",\"teknoloji\"]",
                            TargetWord = "Bilgisayar"
                        },
                        new
                        {
                            Id = new Guid("e3a8b9c0-3456-7890-12ef-1234567890ab"),
                            Category = "Teknoloji",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 3,
                            IsActive = true,
                            TabuWords = "[\"AI\",\"makine\",\"\\u00F6\\u011Frenme\",\"algoritma\",\"robot\"]",
                            TargetWord = "Yapay Zeka"
                        },
                        new
                        {
                            Id = new Guid("a3333333-3333-3333-3333-333333333333"),
                            Category = "Teknoloji",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 1,
                            IsActive = true,
                            TabuWords = "[\"aramak\",\"konu\\u015Fmak\",\"numara\",\"mobil\",\"ekran\"]",
                            TargetWord = "Telefon"
                        },
                        new
                        {
                            Id = new Guid("a4444444-4444-4444-4444-444444444444"),
                            Category = "Teknoloji",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 2,
                            IsActive = true,
                            TabuWords = "[\"web\",\"a\\u011F\",\"ba\\u011Flant\\u0131\",\"site\",\"\\u00E7evrimi\\u00E7i\"]",
                            TargetWord = "İnternet"
                        },
                        new
                        {
                            Id = new Guid("a5555555-5555-5555-5555-555555555555"),
                            Category = "Bilim",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 1,
                            IsActive = true,
                            TabuWords = "[\"\\u0131\\u015F\\u0131k\",\"s\\u0131cak\",\"y\\u0131ld\\u0131z\",\"g\\u00FCnd\\u00FCz\",\"enerji\"]",
                            TargetWord = "Güneş"
                        },
                        new
                        {
                            Id = new Guid("a6666666-6666-6666-6666-666666666666"),
                            Category = "Bilim",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 3,
                            IsActive = true,
                            TabuWords = "[\"gen\",\"h\\u00FCcre\",\"kal\\u0131t\\u0131m\",\"\\u00E7ift sarmal\",\"biyoloji\"]",
                            TargetWord = "DNA"
                        },
                        new
                        {
                            Id = new Guid("a7777777-7777-7777-7777-777777777777"),
                            Category = "Sanat",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 1,
                            IsActive = true,
                            TabuWords = "[\"boya\",\"tablo\",\"f\\u0131r\\u00E7a\",\"tuval\",\"\\u00E7izmek\"]",
                            TargetWord = "Resim"
                        },
                        new
                        {
                            Id = new Guid("a8888888-8888-8888-8888-888888888888"),
                            Category = "Sanat",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 4,
                            IsActive = true,
                            TabuWords = "[\"Dal\\u00ED\",\"r\\u00FCya\",\"bilin\\u00E7alt\\u0131\",\"ger\\u00E7ek\\u00FCst\\u00FC\",\"sanat ak\\u0131m\\u0131\"]",
                            TargetWord = "Sürrealizm"
                        },
                        new
                        {
                            Id = new Guid("a9999999-9999-9999-9999-999999999999"),
                            Category = "Yemek",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 1,
                            IsActive = true,
                            TabuWords = "[\"hamur\",\"peynir\",\"dilim\",\"\\u0130talyan\",\"f\\u0131r\\u0131n\"]",
                            TargetWord = "Pizza"
                        },
                        new
                        {
                            Id = new Guid("b1111111-1111-1111-1111-111111111111"),
                            Category = "Yemek",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 2,
                            IsActive = true,
                            TabuWords = "[\"tatl\\u0131\",\"yufka\",\"\\u015Ferbet\",\"f\\u0131st\\u0131k\",\"Gaziantep\"]",
                            TargetWord = "Baklava"
                        },
                        new
                        {
                            Id = new Guid("b2222222-2222-2222-2222-222222222222"),
                            Category = "Spor",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 1,
                            IsActive = true,
                            TabuWords = "[\"top\",\"gol\",\"kaleci\",\"stadyum\",\"ma\\u00E7\"]",
                            TargetWord = "Futbol"
                        },
                        new
                        {
                            Id = new Guid("b3333333-3333-3333-3333-333333333333"),
                            Category = "Spor",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 2,
                            IsActive = true,
                            TabuWords = "[\"halka\",\"madalya\",\"spor\",\"me\\u015Fale\",\"yar\\u0131\\u015Fma\"]",
                            TargetWord = "Olimpiyat"
                        },
                        new
                        {
                            Id = new Guid("b4444444-4444-4444-4444-444444444444"),
                            Category = "Tarih",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 2,
                            IsActive = true,
                            TabuWords = "[\"M\\u0131s\\u0131r\",\"firavun\",\"ta\\u015F\",\"\\u00FC\\u00E7gen\",\"antik\"]",
                            TargetWord = "Piramit"
                        },
                        new
                        {
                            Id = new Guid("b5555555-5555-5555-5555-555555555555"),
                            Category = "Doğa",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 2,
                            IsActive = true,
                            TabuWords = "[\"lav\",\"patlama\",\"da\\u011F\",\"magma\",\"k\\u00FCl\"]",
                            TargetWord = "Yanardağ"
                        },
                        new
                        {
                            Id = new Guid("b6666666-6666-6666-6666-666666666666"),
                            Category = "Müzik",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 1,
                            IsActive = true,
                            TabuWords = "[\"tel\",\"akort\",\"\\u00E7almak\",\"m\\u00FCzik\",\"pena\"]",
                            TargetWord = "Gitar"
                        },
                        new
                        {
                            Id = new Guid("b7777777-7777-7777-7777-777777777777"),
                            Category = "Müzik",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 3,
                            IsActive = true,
                            TabuWords = "[\"\\u015Fark\\u0131\",\"sahne\",\"soprano\",\"orkestra\",\"tiyatro\"]",
                            TargetWord = "Opera"
                        },
                        new
                        {
                            Id = new Guid("c1000001-0001-0001-0001-000000000001"),
                            Category = "Yemek",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 1,
                            IsActive = true,
                            TabuWords = "[\"et\",\"\\u015Fi\\u015F\",\"\\u0131zgara\",\"Adana\",\"mangal\"]",
                            TargetWord = "Kebap"
                        },
                        new
                        {
                            Id = new Guid("c1000001-0001-0001-0001-000000000002"),
                            Category = "Yemek",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 2,
                            IsActive = true,
                            TabuWords = "[\"Japon\",\"pirin\\u00E7\",\"bal\\u0131k\",\"soya sosu\",\"\\u00E7i\\u011F\"]",
                            TargetWord = "Sushi"
                        },
                        new
                        {
                            Id = new Guid("c1000001-0001-0001-0001-000000000003"),
                            Category = "Yemek",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 1,
                            IsActive = true,
                            TabuWords = "[\"so\\u011Fuk\",\"tatl\\u0131\",\"k\\u00FClah\",\"s\\u00FCt\",\"vanilya\"]",
                            TargetWord = "Dondurma"
                        },
                        new
                        {
                            Id = new Guid("c1000001-0001-0001-0001-000000000004"),
                            Category = "Yemek",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 1,
                            IsActive = true,
                            TabuWords = "[\"demlik\",\"bardak\",\"s\\u0131cak\",\"\\u015Feker\",\"\\u00E7aydanl\\u0131k\"]",
                            TargetWord = "Çay"
                        },
                        new
                        {
                            Id = new Guid("c1000001-0001-0001-0001-000000000005"),
                            Category = "Yemek",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 1,
                            IsActive = true,
                            TabuWords = "[\"fincan\",\"kafein\",\"T\\u00FCrk\",\"espresso\",\"\\u00E7ekirdek\"]",
                            TargetWord = "Kahve"
                        },
                        new
                        {
                            Id = new Guid("c1000001-0001-0001-0001-000000000006"),
                            Category = "Yemek",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 1,
                            IsActive = true,
                            TabuWords = "[\"ince\",\"hamur\",\"k\\u0131yma\",\"limon\",\"rulo\"]",
                            TargetWord = "Lahmacun"
                        },
                        new
                        {
                            Id = new Guid("c1000001-0001-0001-0001-000000000007"),
                            Category = "Yemek",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 2,
                            IsActive = true,
                            TabuWords = "[\"hamur\",\"k\\u0131yma\",\"yo\\u011Furt\",\"Kayseri\",\"k\\u00FC\\u00E7\\u00FCk\"]",
                            TargetWord = "Mantı"
                        },
                        new
                        {
                            Id = new Guid("c2000001-0001-0001-0001-000000000001"),
                            Category = "Teknoloji",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 1,
                            IsActive = true,
                            TabuWords = "[\"makine\",\"otomat\",\"metal\",\"programlama\",\"android\"]",
                            TargetWord = "Robot"
                        },
                        new
                        {
                            Id = new Guid("c2000001-0001-0001-0001-000000000002"),
                            Category = "Teknoloji",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 2,
                            IsActive = true,
                            TabuWords = "[\"u\\u00E7mak\",\"kumanda\",\"kamera\",\"pervane\",\"insans\\u0131z\"]",
                            TargetWord = "Drone"
                        },
                        new
                        {
                            Id = new Guid("c2000001-0001-0001-0001-000000000003"),
                            Category = "Teknoloji",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 2,
                            IsActive = true,
                            TabuWords = "[\"kablosuz\",\"ba\\u011Flant\\u0131\",\"kulakl\\u0131k\",\"e\\u015Fle\\u015Ftirme\",\"sinyal\"]",
                            TargetWord = "Bluetooth"
                        },
                        new
                        {
                            Id = new Guid("c2000001-0001-0001-0001-000000000004"),
                            Category = "Teknoloji",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 1,
                            IsActive = true,
                            TabuWords = "[\"g\\u00FCvenlik\",\"giri\\u015F\",\"parola\",\"karakter\",\"gizli\"]",
                            TargetWord = "Şifre"
                        },
                        new
                        {
                            Id = new Guid("c2000001-0001-0001-0001-000000000005"),
                            Category = "Teknoloji",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 1,
                            IsActive = true,
                            TabuWords = "[\"payla\\u015F\\u0131m\",\"be\\u011Feni\",\"takip\",\"Instagram\",\"g\\u00F6nderi\"]",
                            TargetWord = "Sosyal Medya"
                        },
                        new
                        {
                            Id = new Guid("c3000001-0001-0001-0001-000000000001"),
                            Category = "Spor",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 1,
                            IsActive = true,
                            TabuWords = "[\"pota\",\"top\",\"sma\\u00E7\",\"NBA\",\"say\\u0131\"]",
                            TargetWord = "Basketbol"
                        },
                        new
                        {
                            Id = new Guid("c3000001-0001-0001-0001-000000000002"),
                            Category = "Spor",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 1,
                            IsActive = true,
                            TabuWords = "[\"raket\",\"top\",\"kort\",\"servis\",\"set\"]",
                            TargetWord = "Tenis"
                        },
                        new
                        {
                            Id = new Guid("c3000001-0001-0001-0001-000000000003"),
                            Category = "Spor",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 1,
                            IsActive = true,
                            TabuWords = "[\"havuz\",\"su\",\"kula\\u00E7\",\"mayo\",\"kulvar\"]",
                            TargetWord = "Yüzme"
                        },
                        new
                        {
                            Id = new Guid("c3000001-0001-0001-0001-000000000004"),
                            Category = "Spor",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 2,
                            IsActive = true,
                            TabuWords = "[\"ko\\u015Fu\",\"42 km\",\"dayan\\u0131kl\\u0131l\\u0131k\",\"yar\\u0131\\u015F\",\"parkur\"]",
                            TargetWord = "Maraton"
                        },
                        new
                        {
                            Id = new Guid("c3000001-0001-0001-0001-000000000005"),
                            Category = "Spor",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 1,
                            IsActive = true,
                            TabuWords = "[\"file\",\"sma\\u00E7\",\"pas\",\"top\",\"set\"]",
                            TargetWord = "Voleybol"
                        },
                        new
                        {
                            Id = new Guid("c4000001-0001-0001-0001-000000000001"),
                            Category = "Bilim",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 2,
                            IsActive = true,
                            TabuWords = "[\"\\u00E7ekirdek\",\"elektron\",\"proton\",\"k\\u00FC\\u00E7\\u00FCk\",\"element\"]",
                            TargetWord = "Atom"
                        },
                        new
                        {
                            Id = new Guid("c4000001-0001-0001-0001-000000000002"),
                            Category = "Bilim",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 1,
                            IsActive = true,
                            TabuWords = "[\"g\\u00F6zlem\",\"uzay\",\"mercek\",\"y\\u0131ld\\u0131z\",\"b\\u00FCy\\u00FCtmek\"]",
                            TargetWord = "Teleskop"
                        },
                        new
                        {
                            Id = new Guid("c4000001-0001-0001-0001-000000000003"),
                            Category = "Bilim",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 2,
                            IsActive = true,
                            TabuWords = "[\"fay\",\"sars\\u0131nt\\u0131\",\"b\\u00FCy\\u00FCkl\\u00FCk\",\"Richter\",\"y\\u0131k\\u0131m\"]",
                            TargetWord = "Deprem"
                        },
                        new
                        {
                            Id = new Guid("c4000001-0001-0001-0001-000000000004"),
                            Category = "Bilim",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 3,
                            IsActive = true,
                            TabuWords = "[\"uzay\",\"\\u00E7ekim\",\"\\u0131\\u015F\\u0131k\",\"y\\u0131ld\\u0131z\",\"galaksi\"]",
                            TargetWord = "Karadelik"
                        },
                        new
                        {
                            Id = new Guid("c4000001-0001-0001-0001-000000000005"),
                            Category = "Bilim",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 3,
                            IsActive = true,
                            TabuWords = "[\"Darwin\",\"do\\u011Fal se\\u00E7ilim\",\"t\\u00FCr\",\"adaptasyon\",\"mutasyon\"]",
                            TargetWord = "Evrim"
                        },
                        new
                        {
                            Id = new Guid("c5000001-0001-0001-0001-000000000001"),
                            Category = "Doğa",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 1,
                            IsActive = true,
                            TabuWords = "[\"renk\",\"ya\\u011Fmur\",\"g\\u00FCne\\u015F\",\"yedi\",\"g\\u00F6ky\\u00FCz\\u00FC\"]",
                            TargetWord = "Gökkuşağı"
                        },
                        new
                        {
                            Id = new Guid("c5000001-0001-0001-0001-000000000002"),
                            Category = "Doğa",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 1,
                            IsActive = true,
                            TabuWords = "[\"deniz\",\"su\",\"derin\",\"dalga\",\"Pasifik\"]",
                            TargetWord = "Okyanus"
                        },
                        new
                        {
                            Id = new Guid("c5000001-0001-0001-0001-000000000003"),
                            Category = "Doğa",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 1,
                            IsActive = true,
                            TabuWords = "[\"a\\u011Fa\\u00E7\",\"ye\\u015Fil\",\"do\\u011Fa\",\"hayvan\",\"yaprak\"]",
                            TargetWord = "Orman"
                        },
                        new
                        {
                            Id = new Guid("c5000001-0001-0001-0001-000000000004"),
                            Category = "Doğa",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 2,
                            IsActive = true,
                            TabuWords = "[\"su\",\"d\\u00FC\\u015Fmek\",\"kayal\\u0131k\",\"do\\u011Fa\",\"akmak\"]",
                            TargetWord = "Şelale"
                        },
                        new
                        {
                            Id = new Guid("c5000001-0001-0001-0001-000000000005"),
                            Category = "Doğa",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 2,
                            IsActive = true,
                            TabuWords = "[\"buz\",\"so\\u011Fuk\",\"penguen\",\"kuzey\",\"g\\u00FCney\"]",
                            TargetWord = "Kutup"
                        },
                        new
                        {
                            Id = new Guid("c6000001-0001-0001-0001-000000000001"),
                            Category = "Tarih",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 2,
                            IsActive = true,
                            TabuWords = "[\"padi\\u015Fah\",\"imparatorluk\",\"\\u0130stanbul\",\"fetih\",\"sultan\"]",
                            TargetWord = "Osmanlı"
                        },
                        new
                        {
                            Id = new Guid("c6000001-0001-0001-0001-000000000002"),
                            Category = "Tarih",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 1,
                            IsActive = true,
                            TabuWords = "[\"Cumhuriyet\",\"kurucu\",\"lider\",\"Ankara\",\"devrim\"]",
                            TargetWord = "Atatürk"
                        },
                        new
                        {
                            Id = new Guid("c6000001-0001-0001-0001-000000000003"),
                            Category = "Tarih",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 1,
                            IsActive = true,
                            TabuWords = "[\"nesli t\\u00FCkenmi\\u015F\",\"dev\",\"s\\u00FCr\\u00FCngen\",\"fosil\",\"Jura\"]",
                            TargetWord = "Dinozor"
                        },
                        new
                        {
                            Id = new Guid("c6000001-0001-0001-0001-000000000004"),
                            Category = "Tarih",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 2,
                            IsActive = true,
                            TabuWords = "[\"Roma\",\"arena\",\"d\\u00F6v\\u00FC\\u015F\",\"k\\u0131l\\u0131\\u00E7\",\"k\\u00F6le\"]",
                            TargetWord = "Gladyatör"
                        },
                        new
                        {
                            Id = new Guid("c6000001-0001-0001-0001-000000000005"),
                            Category = "Tarih",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 3,
                            IsActive = true,
                            TabuWords = "[\"at\",\"sava\\u015F\",\"Yunan\",\"hile\",\"antik\"]",
                            TargetWord = "Truva"
                        },
                        new
                        {
                            Id = new Guid("c7000001-0001-0001-0001-000000000001"),
                            Category = "Sanat",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 1,
                            IsActive = true,
                            TabuWords = "[\"mermer\",\"yontmak\",\"sanat\\u00E7\\u0131\",\"m\\u00FCze\",\"\\u00FC\\u00E7 boyutlu\"]",
                            TargetWord = "Heykel"
                        },
                        new
                        {
                            Id = new Guid("c7000001-0001-0001-0001-000000000002"),
                            Category = "Sanat",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 2,
                            IsActive = true,
                            TabuWords = "[\"dans\",\"parmak ucu\",\"sahne\",\"ku\\u011Fu\",\"tutu\"]",
                            TargetWord = "Bale"
                        },
                        new
                        {
                            Id = new Guid("c7000001-0001-0001-0001-000000000003"),
                            Category = "Sanat",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 3,
                            IsActive = true,
                            TabuWords = "[\"su\",\"boya\",\"desen\",\"geleneksel\",\"ka\\u011F\\u0131t\"]",
                            TargetWord = "Ebru"
                        },
                        new
                        {
                            Id = new Guid("c8000001-0001-0001-0001-000000000001"),
                            Category = "Müzik",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 1,
                            IsActive = true,
                            TabuWords = "[\"tu\\u015F\",\"siyah beyaz\",\"\\u00E7almak\",\"kuyruklu\",\"nota\"]",
                            TargetWord = "Piyano"
                        },
                        new
                        {
                            Id = new Guid("c8000001-0001-0001-0001-000000000002"),
                            Category = "Müzik",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 1,
                            IsActive = true,
                            TabuWords = "[\"vurmak\",\"ritim\",\"baget\",\"ses\",\"tempo\"]",
                            TargetWord = "Davul"
                        },
                        new
                        {
                            Id = new Guid("c8000001-0001-0001-0001-000000000003"),
                            Category = "Müzik",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 2,
                            IsActive = true,
                            TabuWords = "[\"s\\u00F6z\",\"ritim\",\"hip-hop\",\"beat\",\"kafiye\"]",
                            TargetWord = "Rap"
                        },
                        new
                        {
                            Id = new Guid("c9000001-0001-0001-0001-000000000001"),
                            Category = "Ulaşım",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 1,
                            IsActive = true,
                            TabuWords = "[\"yeralt\\u0131\",\"istasyon\",\"ray\",\"\\u015Fehir\",\"ula\\u015F\\u0131m\"]",
                            TargetWord = "Metro"
                        },
                        new
                        {
                            Id = new Guid("c9000001-0001-0001-0001-000000000002"),
                            Category = "Ulaşım",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 1,
                            IsActive = true,
                            TabuWords = "[\"deniz\",\"liman\",\"kaptan\",\"yolcu\",\"g\\u00FCverte\"]",
                            TargetWord = "Gemi"
                        },
                        new
                        {
                            Id = new Guid("c9000001-0001-0001-0001-000000000003"),
                            Category = "Ulaşım",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 2,
                            IsActive = true,
                            TabuWords = "[\"uzay\",\"f\\u0131rlatmak\",\"NASA\",\"yak\\u0131t\",\"h\\u0131z\"]",
                            TargetWord = "Roket"
                        },
                        new
                        {
                            Id = new Guid("d1000001-0001-0001-0001-000000000001"),
                            Category = "Coğrafya",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 1,
                            IsActive = true,
                            TabuWords = "[\"bo\\u011Faz\",\"k\\u00F6pr\\u00FC\",\"iki k\\u0131ta\",\"cami\",\"b\\u00FCy\\u00FCk\\u015Fehir\"]",
                            TargetWord = "İstanbul"
                        },
                        new
                        {
                            Id = new Guid("d1000001-0001-0001-0001-000000000002"),
                            Category = "Coğrafya",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 2,
                            IsActive = true,
                            TabuWords = "[\"peri bacas\\u0131\",\"balon\",\"Nev\\u015Fehir\",\"yeralt\\u0131\",\"kayal\\u0131k\"]",
                            TargetWord = "Kapadokya"
                        },
                        new
                        {
                            Id = new Guid("d1000001-0001-0001-0001-000000000003"),
                            Category = "Coğrafya",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 2,
                            IsActive = true,
                            TabuWords = "[\"buz\",\"kutup\",\"so\\u011Fuk\",\"penguen\",\"k\\u0131ta\"]",
                            TargetWord = "Antarktika"
                        },
                        new
                        {
                            Id = new Guid("d1000001-0001-0001-0001-000000000004"),
                            Category = "Coğrafya",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 2,
                            IsActive = true,
                            TabuWords = "[\"travertenler\",\"beyaz\",\"termal\",\"Denizli\",\"UNESCO\"]",
                            TargetWord = "Pamukkale"
                        },
                        new
                        {
                            Id = new Guid("d2000001-0001-0001-0001-000000000001"),
                            Category = "Meslekler",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 1,
                            IsActive = true,
                            TabuWords = "[\"hastane\",\"tedavi\",\"ila\\u00E7\",\"muayene\",\"stetoskop\"]",
                            TargetWord = "Doktor"
                        },
                        new
                        {
                            Id = new Guid("d2000001-0001-0001-0001-000000000002"),
                            Category = "Meslekler",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 2,
                            IsActive = true,
                            TabuWords = "[\"uzay\",\"roket\",\"NASA\",\"a\\u011F\\u0131rl\\u0131ks\\u0131z\",\"kask\"]",
                            TargetWord = "Astronot"
                        },
                        new
                        {
                            Id = new Guid("d2000001-0001-0001-0001-000000000003"),
                            Category = "Meslekler",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 1,
                            IsActive = true,
                            TabuWords = "[\"bina\",\"\\u00E7izim\",\"proje\",\"tasar\\u0131m\",\"yap\\u0131\"]",
                            TargetWord = "Mimar"
                        },
                        new
                        {
                            Id = new Guid("d2000001-0001-0001-0001-000000000004"),
                            Category = "Meslekler",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 1,
                            IsActive = true,
                            TabuWords = "[\"mutfak\",\"yemek\",\"pi\\u015Firmek\",\"restoran\",\"tarif\"]",
                            TargetWord = "Aşçı"
                        },
                        new
                        {
                            Id = new Guid("d2000001-0001-0001-0001-000000000005"),
                            Category = "Meslekler",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 2,
                            IsActive = true,
                            TabuWords = "[\"ipucu\",\"soru\\u015Fturma\",\"cinayet\",\"b\\u00FCy\\u00FCte\\u00E7\",\"su\\u00E7\"]",
                            TargetWord = "Dedektif"
                        },
                        new
                        {
                            Id = new Guid("d3000001-0001-0001-0001-000000000001"),
                            Category = "Hayvanlar",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 1,
                            IsActive = true,
                            TabuWords = "[\"deniz\",\"zeki\",\"atlama\",\"memeli\",\"gri\"]",
                            TargetWord = "Yunus"
                        },
                        new
                        {
                            Id = new Guid("d3000001-0001-0001-0001-000000000002"),
                            Category = "Hayvanlar",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 1,
                            IsActive = true,
                            TabuWords = "[\"ku\\u015F\",\"y\\u0131rt\\u0131c\\u0131\",\"kanat\",\"g\\u00F6ky\\u00FCz\\u00FC\",\"pen\\u00E7e\"]",
                            TargetWord = "Kartal"
                        },
                        new
                        {
                            Id = new Guid("d3000001-0001-0001-0001-000000000003"),
                            Category = "Hayvanlar",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 2,
                            IsActive = true,
                            TabuWords = "[\"renk de\\u011Fi\\u015Ftirmek\",\"s\\u00FCr\\u00FCngen\",\"dil\",\"kamufle\",\"g\\u00F6z\"]",
                            TargetWord = "Bukalemun"
                        },
                        new
                        {
                            Id = new Guid("d3000001-0001-0001-0001-000000000004"),
                            Category = "Hayvanlar",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 1,
                            IsActive = true,
                            TabuWords = "[\"hortum\",\"b\\u00FCy\\u00FCk\",\"fildi\\u015Fi\",\"Afrika\",\"haf\\u0131za\"]",
                            TargetWord = "Fil"
                        },
                        new
                        {
                            Id = new Guid("d3000001-0001-0001-0001-000000000005"),
                            Category = "Hayvanlar",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 2,
                            IsActive = true,
                            TabuWords = "[\"sekiz\",\"kol\",\"deniz\",\"m\\u00FCrekkep\",\"y\\u00FCzmek\"]",
                            TargetWord = "Ahtapot"
                        },
                        new
                        {
                            Id = new Guid("d4000001-0001-0001-0001-000000000001"),
                            Category = "Eğlence",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 1,
                            IsActive = true,
                            TabuWords = "[\"palya\\u00E7o\",\"akrobat\",\"g\\u00F6steri\",\"\\u00E7ad\\u0131r\",\"hayvan\"]",
                            TargetWord = "Sirk"
                        },
                        new
                        {
                            Id = new Guid("d4000001-0001-0001-0001-000000000002"),
                            Category = "Eğlence",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 1,
                            IsActive = true,
                            TabuWords = "[\"\\u015Fark\\u0131\",\"mikrofon\",\"ekran\",\"s\\u00F6z\",\"e\\u011Flence\"]",
                            TargetWord = "Karaoke"
                        },
                        new
                        {
                            Id = new Guid("d4000001-0001-0001-0001-000000000003"),
                            Category = "Eğlence",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 1,
                            IsActive = true,
                            TabuWords = "[\"d\\u00F6nme dolap\",\"h\\u0131z treni\",\"e\\u011Flence\",\"bilet\",\"atl\\u0131kar\\u0131nca\"]",
                            TargetWord = "Lunapark"
                        },
                        new
                        {
                            Id = new Guid("d5000001-0001-0001-0001-000000000001"),
                            Category = "Kavramlar",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 3,
                            IsActive = true,
                            TabuWords = "[\"ge\\u00E7mi\\u015F\",\"\\u00F6zlem\",\"an\\u0131\",\"eski\",\"hat\\u0131ra\"]",
                            TargetWord = "Nostalji"
                        },
                        new
                        {
                            Id = new Guid("d5000001-0001-0001-0001-000000000002"),
                            Category = "Kavramlar",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 2,
                            IsActive = true,
                            TabuWords = "[\"oy\",\"halk\",\"se\\u00E7im\",\"\\u00F6zg\\u00FCrl\\u00FCk\",\"y\\u00F6netim\"]",
                            TargetWord = "Demokrasi"
                        },
                        new
                        {
                            Id = new Guid("d5000001-0001-0001-0001-000000000003"),
                            Category = "Kavramlar",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 3,
                            IsActive = true,
                            TabuWords = "[\"anlama\",\"duygu\",\"kar\\u015F\\u0131 taraf\",\"hissetmek\",\"ba\\u015Fkas\\u0131\"]",
                            TargetWord = "Empati"
                        },
                        new
                        {
                            Id = new Guid("d5000001-0001-0001-0001-000000000004"),
                            Category = "Kavramlar",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 4,
                            IsActive = true,
                            TabuWords = "[\"tersine\",\"alay\",\"anlam\",\"s\\u00F6z\",\"beklenti\"]",
                            TargetWord = "Ironi"
                        },
                        new
                        {
                            Id = new Guid("d6000001-0001-0001-0001-000000000001"),
                            Category = "Sinema",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 2,
                            IsActive = true,
                            TabuWords = "[\"\\u00F6d\\u00FCl\",\"Hollywood\",\"film\",\"heykelcik\",\"t\\u00F6ren\"]",
                            TargetWord = "Oscar"
                        },
                        new
                        {
                            Id = new Guid("d6000001-0001-0001-0001-000000000002"),
                            Category = "Sinema",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 1,
                            IsActive = true,
                            TabuWords = "[\"b\\u00F6l\\u00FCm\",\"sezon\",\"televizyon\",\"izlemek\",\"oyuncu\"]",
                            TargetWord = "Dizi"
                        },
                        new
                        {
                            Id = new Guid("d6000001-0001-0001-0001-000000000003"),
                            Category = "Sinema",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 2,
                            IsActive = true,
                            TabuWords = "[\"\\u00E7izgi film\",\"karakter\",\"Pixar\",\"canland\\u0131rma\",\"Disney\"]",
                            TargetWord = "Animasyon"
                        },
                        new
                        {
                            Id = new Guid("d7000001-0001-0001-0001-000000000001"),
                            Category = "Edebiyat",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 1,
                            IsActive = true,
                            TabuWords = "[\"kitap\",\"yazar\",\"sayfa\",\"okumak\",\"hikaye\"]",
                            TargetWord = "Roman"
                        },
                        new
                        {
                            Id = new Guid("d7000001-0001-0001-0001-000000000002"),
                            Category = "Edebiyat",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 2,
                            IsActive = true,
                            TabuWords = "[\"m\\u0131sra\",\"kafiye\",\"dize\",\"\\u015Fair\",\"\\u00F6l\\u00E7\\u00FC\"]",
                            TargetWord = "Şiir"
                        },
                        new
                        {
                            Id = new Guid("d7000001-0001-0001-0001-000000000003"),
                            Category = "Edebiyat",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 1,
                            IsActive = true,
                            TabuWords = "[\"\\u00E7ocuk\",\"prenses\",\"bir varm\\u0131\\u015F\",\"hayal\",\"ejderha\"]",
                            TargetWord = "Masal"
                        });
                });

            modelBuilder.Entity("TabuAI.Domain.Entities.ActivityLog", b =>
                {
                    b.HasOne("TabuAI.Domain.Entities.User", "User")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TabuAI.Domain.Entities.Challenge", b =>
                {
                    b.HasOne("TabuAI.Domain.Entities.User", "Challenged")
                        .WithMany()
                        .HasForeignKey("ChallengedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TabuAI.Domain.Entities.User", "Challenger")
                        .WithMany()
                        .HasForeignKey("ChallengerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TabuAI.Domain.Entities.VersusGame", "VersusGame")
                        .WithMany()
                        .HasForeignKey("VersusGameId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TabuAI.Domain.Entities.Word", "Word")
                        .WithMany()
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Challenged");

                    b.Navigation("Challenger");

                    b.Navigation("VersusGame");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("TabuAI.Domain.Entities.Friendship", b =>
                {
                    b.HasOne("TabuAI.Domain.Entities.User", "Addressee")
                        .WithMany("ReceivedFriendRequests")
                        .HasForeignKey("AddresseeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TabuAI.Domain.Entities.User", "Requester")
                        .WithMany("SentFriendRequests")
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Addressee");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("TabuAI.Domain.Entities.GameAttempt", b =>
                {
                    b.HasOne("TabuAI.Domain.Entities.GameSession", "GameSession")
                        .WithMany("Attempts")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameSession");
                });

            modelBuilder.Entity("TabuAI.Domain.Entities.GameSession", b =>
                {
                    b.HasOne("TabuAI.Domain.Entities.User", "User")
                        .WithMany("GameSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TabuAI.Domain.Entities.Word", "Word")
                        .WithMany("GameSessions")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("TabuAI.Domain.Entities.UserBadge", b =>
                {
                    b.HasOne("TabuAI.Domain.Entities.Badge", "Badge")
                        .WithMany("UserBadges")
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TabuAI.Domain.Entities.User", "User")
                        .WithMany("UserBadges")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TabuAI.Domain.Entities.UserStatistic", b =>
                {
                    b.HasOne("TabuAI.Domain.Entities.User", "User")
                        .WithMany("UserStatistics")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TabuAI.Domain.Entities.VersusGame", b =>
                {
                    b.HasOne("TabuAI.Domain.Entities.GameSession", "Player1GameSession")
                        .WithMany()
                        .HasForeignKey("Player1GameSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TabuAI.Domain.Entities.User", "Player1")
                        .WithMany()
                        .HasForeignKey("Player1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TabuAI.Domain.Entities.GameSession", "Player2GameSession")
                        .WithMany()
                        .HasForeignKey("Player2GameSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TabuAI.Domain.Entities.User", "Player2")
                        .WithMany()
                        .HasForeignKey("Player2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TabuAI.Domain.Entities.Word", "Word")
                        .WithMany()
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Player1");

                    b.Navigation("Player1GameSession");

                    b.Navigation("Player2");

                    b.Navigation("Player2GameSession");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("TabuAI.Domain.Entities.Badge", b =>
                {
                    b.Navigation("UserBadges");
                });

            modelBuilder.Entity("TabuAI.Domain.Entities.GameSession", b =>
                {
                    b.Navigation("Attempts");
                });

            modelBuilder.Entity("TabuAI.Domain.Entities.User", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("GameSessions");

                    b.Navigation("ReceivedFriendRequests");

                    b.Navigation("SentFriendRequests");

                    b.Navigation("UserBadges");

                    b.Navigation("UserStatistics");
                });

            modelBuilder.Entity("TabuAI.Domain.Entities.Word", b =>
                {
                    b.Navigation("GameSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
