// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TabuAI.Infrastructure.Data;

#nullable disable

namespace TabuAI.Infrastructure.Migrations
{
    [DbContext(typeof(TabuAIDbContext))]
    [Migration("20260219212141_AddUserRoleAndAdminSeed")]
    partial class AddUserRoleAndAdminSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TabuAI.Domain.Entities.Badge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("RequiredValue")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Badges");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f4a9b0c1-4567-8901-2301-234567890abc"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "İlk oyununu tamamladın!",
                            IconUrl = "/badges/first-game.svg",
                            IsActive = true,
                            Name = "İlk Adım",
                            RequiredValue = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("a5b0c1d2-5678-9012-3412-34567890abcd"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "10 mükemmel prompt yazdın!",
                            IconUrl = "/badges/perfect-prompts.svg",
                            IsActive = true,
                            Name = "Prompt Ustası",
                            RequiredValue = 10,
                            Type = 3
                        },
                        new
                        {
                            Id = new Guid("b6c1d2e3-6789-0123-4523-4567890abcde"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "50 oyunda hiç tabu kelime kullanmadın!",
                            IconUrl = "/badges/tabu-avoidance.svg",
                            IsActive = true,
                            Name = "Tabu Kaçkını",
                            RequiredValue = 50,
                            Type = 5
                        });
                });

            modelBuilder.Entity("TabuAI.Domain.Entities.GameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AiFeedback")
                        .HasColumnType("text");

                    b.Property<string>("AiResponse")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCorrectGuess")
                        .HasColumnType("boolean");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<int?>("PromptQuality")
                        .HasColumnType("integer");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Suggestions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("TimeSpent")
                        .HasColumnType("interval");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserPrompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WordId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WordId");

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("TabuAI.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("integer");

                    b.Property<int>("GamesWon")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("TotalScore")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Admin User",
                            Email = "admin@tabuai.com",
                            GamesPlayed = 0,
                            GamesWon = 0,
                            IsActive = true,
                            Level = 1,
                            PasswordHash = "$2a$11$N9qo8uLOickgx2ZMRZoMyeIjZAgwd966VQRfAk5U5Z6.t.15v8vS6",
                            Role = 2,
                            TotalScore = 0,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("TabuAI.Domain.Entities.UserBadge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BadgeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EarnedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BadgeId");

                    b.HasIndex("UserId", "BadgeId")
                        .IsUnique();

                    b.ToTable("UserBadges");
                });

            modelBuilder.Entity("TabuAI.Domain.Entities.UserStatistic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("MetricName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserStatistics");
                });

            modelBuilder.Entity("TabuAI.Domain.Entities.Word", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("TabuWords")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetWord")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Words");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d1b6a7b8-1234-5678-90ab-cdef12345678"),
                            Category = "Ulaşım",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 1,
                            IsActive = true,
                            TabuWords = "[\"hava\",\"kanat\",\"yolcu\",\"pilot\",\"u\\u00E7mak\"]",
                            TargetWord = "Uçak"
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-111111111111"),
                            Category = "Ulaşım",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 1,
                            IsActive = true,
                            TabuWords = "[\"ray\",\"vagon\",\"istasyon\",\"lokomotif\",\"bilet\"]",
                            TargetWord = "Tren"
                        },
                        new
                        {
                            Id = new Guid("a2222222-2222-2222-2222-222222222222"),
                            Category = "Ulaşım",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 1,
                            IsActive = true,
                            TabuWords = "[\"pedal\",\"tekerlek\",\"zincir\",\"gidon\",\"s\\u00FCrmek\"]",
                            TargetWord = "Bisiklet"
                        },
                        new
                        {
                            Id = new Guid("c2a7b8c9-2345-6789-01cd-ef1234567890"),
                            Category = "Teknoloji",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 1,
                            IsActive = true,
                            TabuWords = "[\"ekran\",\"klavye\",\"fare\",\"i\\u015Flemci\",\"teknoloji\"]",
                            TargetWord = "Bilgisayar"
                        },
                        new
                        {
                            Id = new Guid("e3a8b9c0-3456-7890-12ef-1234567890ab"),
                            Category = "Teknoloji",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 3,
                            IsActive = true,
                            TabuWords = "[\"AI\",\"makine\",\"\\u00F6\\u011Frenme\",\"algoritma\",\"robot\"]",
                            TargetWord = "Yapay Zeka"
                        },
                        new
                        {
                            Id = new Guid("a3333333-3333-3333-3333-333333333333"),
                            Category = "Teknoloji",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 1,
                            IsActive = true,
                            TabuWords = "[\"aramak\",\"konu\\u015Fmak\",\"numara\",\"mobil\",\"ekran\"]",
                            TargetWord = "Telefon"
                        },
                        new
                        {
                            Id = new Guid("a4444444-4444-4444-4444-444444444444"),
                            Category = "Teknoloji",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 2,
                            IsActive = true,
                            TabuWords = "[\"web\",\"a\\u011F\",\"ba\\u011Flant\\u0131\",\"site\",\"\\u00E7evrimi\\u00E7i\"]",
                            TargetWord = "İnternet"
                        },
                        new
                        {
                            Id = new Guid("a5555555-5555-5555-5555-555555555555"),
                            Category = "Bilim",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 1,
                            IsActive = true,
                            TabuWords = "[\"\\u0131\\u015F\\u0131k\",\"s\\u0131cak\",\"y\\u0131ld\\u0131z\",\"g\\u00FCnd\\u00FCz\",\"enerji\"]",
                            TargetWord = "Güneş"
                        },
                        new
                        {
                            Id = new Guid("a6666666-6666-6666-6666-666666666666"),
                            Category = "Bilim",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 3,
                            IsActive = true,
                            TabuWords = "[\"gen\",\"h\\u00FCcre\",\"kal\\u0131t\\u0131m\",\"\\u00E7ift sarmal\",\"biyoloji\"]",
                            TargetWord = "DNA"
                        },
                        new
                        {
                            Id = new Guid("a7777777-7777-7777-7777-777777777777"),
                            Category = "Sanat",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 1,
                            IsActive = true,
                            TabuWords = "[\"boya\",\"tablo\",\"f\\u0131r\\u00E7a\",\"tuval\",\"\\u00E7izmek\"]",
                            TargetWord = "Resim"
                        },
                        new
                        {
                            Id = new Guid("a8888888-8888-8888-8888-888888888888"),
                            Category = "Sanat",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 4,
                            IsActive = true,
                            TabuWords = "[\"Dal\\u00ED\",\"r\\u00FCya\",\"bilin\\u00E7alt\\u0131\",\"ger\\u00E7ek\\u00FCst\\u00FC\",\"sanat ak\\u0131m\\u0131\"]",
                            TargetWord = "Sürrealizm"
                        },
                        new
                        {
                            Id = new Guid("a9999999-9999-9999-9999-999999999999"),
                            Category = "Yemek",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 1,
                            IsActive = true,
                            TabuWords = "[\"hamur\",\"peynir\",\"dilim\",\"\\u0130talyan\",\"f\\u0131r\\u0131n\"]",
                            TargetWord = "Pizza"
                        },
                        new
                        {
                            Id = new Guid("b1111111-1111-1111-1111-111111111111"),
                            Category = "Yemek",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 2,
                            IsActive = true,
                            TabuWords = "[\"tatl\\u0131\",\"yufka\",\"\\u015Ferbet\",\"f\\u0131st\\u0131k\",\"Gaziantep\"]",
                            TargetWord = "Baklava"
                        },
                        new
                        {
                            Id = new Guid("b2222222-2222-2222-2222-222222222222"),
                            Category = "Spor",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 1,
                            IsActive = true,
                            TabuWords = "[\"top\",\"gol\",\"kaleci\",\"stadyum\",\"ma\\u00E7\"]",
                            TargetWord = "Futbol"
                        },
                        new
                        {
                            Id = new Guid("b3333333-3333-3333-3333-333333333333"),
                            Category = "Spor",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 2,
                            IsActive = true,
                            TabuWords = "[\"halka\",\"madalya\",\"spor\",\"me\\u015Fale\",\"yar\\u0131\\u015Fma\"]",
                            TargetWord = "Olimpiyat"
                        },
                        new
                        {
                            Id = new Guid("b4444444-4444-4444-4444-444444444444"),
                            Category = "Tarih",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 2,
                            IsActive = true,
                            TabuWords = "[\"M\\u0131s\\u0131r\",\"firavun\",\"ta\\u015F\",\"\\u00FC\\u00E7gen\",\"antik\"]",
                            TargetWord = "Piramit"
                        },
                        new
                        {
                            Id = new Guid("b5555555-5555-5555-5555-555555555555"),
                            Category = "Doğa",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 2,
                            IsActive = true,
                            TabuWords = "[\"lav\",\"patlama\",\"da\\u011F\",\"magma\",\"k\\u00FCl\"]",
                            TargetWord = "Yanardağ"
                        },
                        new
                        {
                            Id = new Guid("b6666666-6666-6666-6666-666666666666"),
                            Category = "Müzik",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 1,
                            IsActive = true,
                            TabuWords = "[\"tel\",\"akort\",\"\\u00E7almak\",\"m\\u00FCzik\",\"pena\"]",
                            TargetWord = "Gitar"
                        },
                        new
                        {
                            Id = new Guid("b7777777-7777-7777-7777-777777777777"),
                            Category = "Müzik",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = 3,
                            IsActive = true,
                            TabuWords = "[\"\\u015Fark\\u0131\",\"sahne\",\"soprano\",\"orkestra\",\"tiyatro\"]",
                            TargetWord = "Opera"
                        });
                });

            modelBuilder.Entity("TabuAI.Domain.Entities.GameSession", b =>
                {
                    b.HasOne("TabuAI.Domain.Entities.User", "User")
                        .WithMany("GameSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TabuAI.Domain.Entities.Word", "Word")
                        .WithMany("GameSessions")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("TabuAI.Domain.Entities.UserBadge", b =>
                {
                    b.HasOne("TabuAI.Domain.Entities.Badge", "Badge")
                        .WithMany("UserBadges")
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TabuAI.Domain.Entities.User", "User")
                        .WithMany("UserBadges")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TabuAI.Domain.Entities.UserStatistic", b =>
                {
                    b.HasOne("TabuAI.Domain.Entities.User", "User")
                        .WithMany("UserStatistics")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TabuAI.Domain.Entities.Badge", b =>
                {
                    b.Navigation("UserBadges");
                });

            modelBuilder.Entity("TabuAI.Domain.Entities.User", b =>
                {
                    b.Navigation("GameSessions");

                    b.Navigation("UserBadges");

                    b.Navigation("UserStatistics");
                });

            modelBuilder.Entity("TabuAI.Domain.Entities.Word", b =>
                {
                    b.Navigation("GameSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
